### PR TITLE
use std::regex instead of boost::regex

### PR DESCRIPTION
**Pull request by planthaber**
Using boost::regex with gcc5 on ubuntu 16.10 results in linker errors, but slam-envire has to be build with gcc5 as libply does not compile using gcc6 and boost 1.61 on ubuntu 16.10.

This way, slam-envire compiles fine

### CODE REVIEW

**Comment by jmachowinski** [comment]
This will result in errors on 14.04, as the gcc version used there does not implement std::regex yet.

**Comment by chhtz** [comment]
Compiles fine for me on Ubuntu 14.04 with g++ 4.8.4 (except for unrelated warnings)

**Comment by chhtz** [comment]
Ok, apparently it compiles but does not work (@jmachowinski pointed me to this https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631):
```
/home/rock/slam/envire$ env_slam6d update test test
WARN: could not read scalar for label
WARN: could not read scalar for label
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
```
With the original boost implementation it does not segfault. Maybe just guard the `#include` by some checks on `__GNUC__` and `__GNUC_MINOR__` (this would still not work with Ubuntu 16.10 and gcc 4.8, however).

**Comment by planthaber** [comment]
libply (used in slam6d) does not compile with gcc6, https://github.com/rock-slam/external-libply/issues/1

The initial solution was to compile libply with gcc5. Which then has errors with boost 1.61, which reporst that regex has an undefiend reference. (uncommenting the slam6d env works though)

**Comment by planthaber** [comment]
Updated the PR, now cmake checks for the gcc version, if 4.9 or bigger (has regex support https://isocpp.org/blog/2014/04/gcc-4.9.0), a define is set to compile using std::regex

**Comment by planthaber** [comment]
push

**Comment by planthaber** [comment]
Anyone willing to merge?

**Comment by planthaber** [comment]
Thanks ,-)
